OUTPUTS = \
	basic/manual/main \
	basic/gen-acyclic-graph/main \
	special/planarization/main \
	system/system-info \
	layout/energy-based/main \
	layout/energy-based/multilevelmixer/fast/main \
	layout/energy-based/multilevelmixer/nice/main \
	layout/energy-based/multilevelmixer/no-twist/main \
	layout/orthogonal/main \
	layout/hierarchical-ranking/main \
	layout/hierarchical/main \
	layout/hypergraph/main

include ../Makefile.inc
